### ISSUE TITLE
Support download mirrors

### ISSUE THREAD

**Issue by castrojo** [powersj/ubuntu-iso-download#1]
It'd be nice if we could specific a mirror either in config or in a flag.

Perhaps consuming https://launchpad.net/ubuntu/+cdmirrors or maybe there's some other programmatic way to get a regional mirror. 

Great tool btw, this is really handy!

**Comment by powersj** [comment]
Hi! Thanks for the report and I appreciate the suggestion. I will take a look to see what the best way to include this as an option as I can see it helping those who are not near the main mirrors.

Those mirrors are of releases.ubuntu.com which will have all the released ISOs for desktop and server. Development release and all flavors will be found on releases.ubuntu.com.

**Comment by powersj** [comment]
Closed with afcb0262b3bf6a0eeb161b20024c2306e9b29182

Thanks again for the idea! I'll publish a new snap shortly.
