### ISSUE TITLE
Feature request (Ubuntu Mini ISO)

### ISSUE THREAD

**Issue by kz6fittycent** [powersj/ubuntu-iso-download#3]
Would it be possible to include the Mini ISO as an option? Here's it's link: http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso

**Comment by powersj** [comment]
# ISO Location

It looks like the ISO is always in the same place across releases. Which means there is no need to track the difference between the development release and supported releases. Here are examples:

- [Precise](http://archive.ubuntu.com/ubuntu/dists/precise/main/installer-amd64/current/images/netboot/mini.iso)
- [Trusty](http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/mini.iso)
- [Xenial](http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/mini.iso)
- [Bionic](http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso)
- [Eoan](http://archive.ubuntu.com/ubuntu/dists/eoan/main/installer-amd64/current/images/netboot/mini.iso)

Essentially the URL pattern becomes:

`http://archive.ubuntu.com/ubuntu/dists/$release/main/installer-$arch/current/images/netboot/mini.iso`

Where the only valid arch is `amd64` or `i386`. I had forgotten we still produced the mini ISO.

# GPG Validation

A directory up in `images`, there are GPG signed validation files. Sure enough, there are SHA256 files that I can use. Examples for Xenial:

- [SHA256SUMS](http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/SHA256SUMS)
- [SHA256SUMS.gpg](http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/SHA256SUMS.gpg)

These can be used to verify the download.

# Steps

- Update argparse to understand 'mini' as a type
- Create mini url ISO subclass to produce URLs for mini ISOs
- Add tests to cover the new URLs

**Comment by powersj** [comment]
b77ec15 closes this! Thank you for the suggestion! I will push a new snap tomorrow, but edge should be building now.
