### ISSUE TITLE
[Feature Request] Extend codename matching to also match release version numbering

### ISSUE THREAD

**Issue by teward** [powersj/ubuntu-iso-download#5]
Some users, myself included if I don't have coffee, don't remember all the codename to version number mappings.

As a result, the LXD mirrors containing the Ubuntu images for LXD containers have aliases in place for mapping numeric versions to actual codenames - case in point `lxc launch ubuntu:18.04 ...` will refer to the Bionic LXD images on the mirror.

It would be nice to add this as a feature to ubuntu-iso-download as well to map the version numbering to the codenames as well.

According to the information I received from you during an IRC privmsg session, you pull the data from meta-releases.  Which also has the version numbers for each code name as well.  Therefore, including this type of mapping shouldn't be too hard.  And would be a good way to expand the current functionality.

(Note that this project / snap was advertised on the [@]ubuntu Twitter feed.)

**Comment by powersj** [comment]
As you may have just noticed my latest commit adds the ability to specify a codename (e.g bionic) or the release value (e.g. 18.04.3). The release value can either contain the point release or omit it, in which case the latest point release will be returned.

I will publish a new snap later today or tomorrow that fully enables this! Thanks again for the request.

**Comment by powersj** [comment]
Seems the builders are really fast on Sunday morning :smiley: Snap enabling this is now released to stable:
125e8ee 2019-11-03 (107)
